# Generated by Django 5.2.8 on 2025-12-14 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transc_name', models.CharField(max_length=100)),
                ('credit', models.IntegerField(null=True)),
                ('debit', models.IntegerField(null=True)),
                ('trans_date', models.DateField()),
                ('description', models.TextField(null=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
