# Generated by Django 5.2.8 on 2025-12-21 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('transaction', '0001_initial'), ('transaction', '0002_rename_transc_name_transaction_account_name_and_more'), ('transaction', '0003_alter_transaction_user'), ('transaction', '0004_alter_transaction_id'), ('transaction', '0005_alter_transaction_id'), ('transaction', '0006_transaction_category')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=100)),
                ('credit', models.IntegerField(null=True)),
                ('debit', models.IntegerField(null=True)),
                ('txn_date', models.DateField()),
                ('description', models.TextField(null=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.CharField(default='uncatogrized', max_length=100)),
            ],
        ),
    ]
