# Generated by Django 5.2.8 on 2025-12-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transc_name',
            new_name='account_name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='trans_date',
            new_name='txn_date',
        ),
    ]
