# Generated by Django 5.2.8 on 2025-12-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
