# Generated by Django 5.2.8 on 2025-12-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
